<?php
$title = 'Add new question';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
// This provides a default CSS class and placeholder text for the title element:
$question = $form->get('question');
$question->setAttribute('class', 'form-control');
$question->setAttribute('placeholder', 'Question');

// This provides a default CSS class and placeholder text for the artist element:
$answer = $form->get('answer');
$answer->setAttribute('class', 'form-control');
$answer->setAttribute('placeholder', 'Answer');

$aq_enabled_yn = $form->get('aq_enabled_yn');
$aq_enabled_yn->setAttribute('class', 'form-control');
$aq_enabled_yn->setAttribute('placeholder', 'AQ Enabled Y/N');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('admin', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>
<div class="form-group">
    <?= $this->formLabel($question) ?>
    <?= $this->formElement($question) ?>
    <?= $this->formElementErrors()->render($question, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($answer) ?>
    <?= $this->formElement($answer) ?>
    <?= $this->formElementErrors()->render($answer, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($aq_enabled_yn) ?>
    <?= $this->formElement($aq_enabled_yn) ?>
    <?= $this->formElementErrors()->render($aq_enabled_yn, ['class' => 'help-block']) ?>
</div>


<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
?>
<div style="width:100%;" align='right'><?php echo $this->frenchCharMap ?></div>