<?php
// module/Question/view/question/question/delete.phtml:

$title = 'Delete question';
$url   = $this->url('admin', ['action' => 'delete', 'id' => $id]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Are you sure that you want to delete this question and answer?
</p><p>
    "<?= $this->escapeHtml($question->question) ?>" 
</p><p>
    "<?= $this->escapeHtml($question->answer) ?>"
</p>

<form action="<?= $url ?>" method="post">
<div class="form-group">
    <input type="hidden" name="id" value="<?= (int) $question->id ?>" />
    <input type="submit" class="btn btn-danger" name="del" value="Yes" />
    <input type="submit" class="btn btn-success" name="del" value="No" />
</div>
</form>
