<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta name="google-signin-client_id" content="960450020562-bij42s8ibvlc72igdaquu8ruengaenf9.apps.googleusercontent.com">
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
        <script src="https://apis.google.com/js/platform.js" async defer></script>
        <script>
            function onSignIn(googleUser) {
                alert('onSignIn');
              var profile = googleUser.getBasicProfile();
              console.log('ID: ' + profile.getId()); // Do not send to your backend! Use an ID token instead.
                console.log('Name: ' + profile.getName());
                console.log('Image URL: ' + profile.getImageUrl());
                console.log('Email: ' + profile.getEmail()); // This is null if the 'email' scope is not present.
            }
            //function sendIdToken(id_token) {
            //    var xhr = new XMLHttpRequest();
            //    xhr.open('POST', '/login/tokensignin');
            //    xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
            //    xhr.onload = function () {
            //        console.log('Signed in as: ' + xhr.responseText);
            //    };
            //    xhr.send('idtoken=' + id_token);
            //}
        </script>
        Hi
        <div class="g-signin2" data-onsuccess="onSignIn"></div>

        <a href="#" onclick="signOut();">Sign out</a>
        <script>
            function signOut() {
                var auth2 = gapi.auth2.getAuthInstance();
                auth2.signOut().then(function () {
                    console.log('User signed out.');
                });
            }
        </script>

        <?php
        // put your code here
        ?>
    </body>
</html>
