
        <script src="https://apis.google.com/js/platform.js" async defer></script>
        
        <script>
            function onSignIn(googleUser) {
                //alert('onSignIn');
                var profile = googleUser.getBasicProfile();
                console.log('ID: ' + profile.getId()); // Do not send to your backend! Use an ID token instead.
                console.log('Name: ' + profile.getName());
                console.log('Image URL: ' + profile.getImageUrl());
                console.log('Email: ' + profile.getEmail()); // This is null if the 'email' scope is not present.
                sendIdToken(profile, googleUser.getAuthResponse().id_token);
            }
            function sendIdToken(profile, id_token) {
                var xhr = new XMLHttpRequest();
                xhr.open('POST', '/tokensignin');
                xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
                xhr.onload = function () {
                    console.log('Signed in as: ' + xhr.responseText);
                    document.location.href = "/";
                };
                xhr.send('idtoken=' + id_token + '&name=' + profile.getName() + '&email=' + profile.getEmail() + '&imageUrl=' + profile.getImageUrl());

            }
        </script>
        
        <div>Please sign-in using one of these providers.</div>
        
        <div class="g-signin2" data-onsuccess="onSignIn" data-visibility="hidden"></div>
      
        <!--<a href="#" onclick="signOut();">Sign out</a>-->
        <script>
            function signOut() {
                var auth2 = gapi.auth2.getAuthInstance();
                auth2.signOut().then(function () {
                    console.log('User signed out.');
                });
            }
        </script>
        <script>
            window.onload = function () {
                var auth2 = gapi.auth2.getAuthInstance();

                // Sign-In
                //auth2.signIn()
                //        .then(onSignIn, function (error) {
                //            alert('Authentication failed.');
                //        });
            };

        </script>
        <?php
        // put your code here
       
 
