<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta name="google-signin-client_id" content="960450020562-bij42s8ibvlc72igdaquu8ruengaenf9.apps.googleusercontent.com">
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
        <script src="https://apis.google.com/js/platform.js" async defer></script>    
        Goodbye
        <div class="g-signin2" data-onsuccess="onSignIn"></div>
        <script>
            function signOut() {
                var auth2 = gapi.auth2.getAuthInstance();
                auth2.signOut().then(function () {
                    console.log('User signed out.');
                    document.location.href = '/';
                },
                        function (error) {
                            console.log('Signout failed ' + error);
                            document.location.href = '/';
                        });
            }
        </script>
        <script>
            window.onload = function () {
                // alert('Goodbye');
                signOut();
            };

        </script>
        <?php
        // put your code here
        ?>
    </body>
</html>
