<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta name="google-signin-client_id" content="960450020562-bij42s8ibvlc72igdaquu8ruengaenf9.apps.googleusercontent.com">
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
       So far so good.
    </body>
</html>
