<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta name="google-signin-client_id" content="960450020562-bij42s8ibvlc72igdaquu8ruengaenf9.apps.googleusercontent.com">
        <meta charset="utf-8">
        <?= $this->headTitle('DGC Rote Learning')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/rl/style.css'))
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <?php
           # $loggedIn = false;
           $this->navigation('navigation')->menu()->findOneBy('label','Sign Out')->setVisible( $loggedIn); 
           $this->navigation('navigation')->menu()->findOneBy('label','Sign In')->setVisible(! $loggedIn); 
        ?>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img style="background-color:white" src="<?= $this->basePath('img/dgc-logo.svg') ?>" height="28" alt="Rote Learning <?= \Application\Module::VERSION ?>"/>&nbsp;Rote Learning 
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <?= $this->navigation('navigation')->menu()
                        ->setMinDepth(0)
                        ->setMaxDepth(0)
                        ->setUlClass('nav navbar-nav') ?>
               </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; 2017 - <?= date('Y') ?> by DGC 100 Ltd. All rights reserved.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
