<?php
$language = $activeQuestion['direction'] == 'AQ' ? 'English' : 'French';
$language = $activeQuestion['direction'] == 'AQ' ? 'English' : 'French';
$title = 'Please translate the question below into ' . $language;
$answerPlaceholder = $language == 'English'
  ? 'Please type your ' . $language . ' translation here. Omit the definite article. eg le chien -> dog'
  :  'Please type your ' . $language . ' translation here. Include the definite article. eg dog -> le chien';

$this->headTitle('Translate Question');
switch ($status) {
    case 'retry':
        $message = 'Sorry. Your answer was incorrect. Please try again.';
        break;
    case 'incorrect':
        $message = 'The correct answer to the last question was: ' . $lastActiveQuestion['answer'];
        break;
    default:
        $message = "";
}
$message_class = ($status == 'incorrect') ? 'bg-danger' : 'bg-info';
?>
<div>
<h3>Score for this session</h3>
<table class="table table-bordered">
<tr>
<td>Number of Questions Asked</td><td>Correct</td><td>Wrong</td>
</tr>
<tr>
<td><?= $score['asked'] ?></td>
<td><?= $score['correct'] ?></td>
<td><?= $score['incorrect'] ?></td>
</tr>
</table>
</div>
<h1><?= $this->escapeHtml($title) ?></h1>
<div><p class="<?= $message_class ?>"><?= $message ?></p></div>
<?php
// This provides a default CSS class and placeholder text for the title element:
$question = $form->get('question');
$question->setAttribute('class', 'form-control');
$question->setAttribute('placeholder', 'Question');

// This provides a default CSS class and placeholder text for the artist element:
$answer = $form->get('answer');
$answer->setAttribute('class', 'form-control');
$answer->setAttribute('placeholder', $answerPlaceholder);

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

// This provides CSS classes for the donotknow button:
$donotknow = $form->get('donotknow');
$donotknow->setAttribute('class', 'btn btn-secondary');

$form->setAttribute('action', $this->url('question', ['action' => 'index']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>
<div class="form-group">
    <?= $this->formLabel($question) ?>
    <?= $this->formElement($question) ?>
    <?= $this->formElementErrors()->render($question, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($answer) ?>
    <?= $this->formElement($answer) ?>
    <?= $this->formElementErrors()->render($answer, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formSubmit($donotknow);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
?>

<div style="width:100%;" align='right'><?php echo $this->frenchCharMap ?></div>

<script type="text/javascript">
  function checkForm()
  {
      document.getElementsByName('answer')[0].value = 'Do not know';
      return true;
  }
</script>
