<?php
$title = 'Translate question';
$this->headTitle($title);
$message_class = $message['type'] == 'incorrect' ? 'bg-danger' : 'bg-info';
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p class="<?= $message_class ?>"><?= $message['message'] ?></p>
<?php
// This provides a default CSS class and placeholder text for the title element:
$question = $form->get('question');
$question->setAttribute('class', 'form-control');
$question->setAttribute('placeholder', 'Question');

// This provides a default CSS class and placeholder text for the artist element:
$answer = $form->get('answer');
$answer->setAttribute('class', 'form-control');
$answer->setAttribute('placeholder', 'Answer');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

// This provides CSS classes for the donotknow button:
$donotknow = $form->get('donotknow');
$donotknow->setAttribute('class', 'btn btn-secondary');

$form->setAttribute('action', $this->url('question', ['action' => 'index']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>
<div class="form-group">
    <?= $this->formLabel($question) ?>
    <?= $this->formElement($question) ?>
    <?= $this->formElementErrors()->render($question, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($answer) ?>
    <?= $this->formElement($answer) ?>
    <?= $this->formElementErrors()->render($answer, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formSubmit($donotknow);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
?>

<script type="text/javascript">
  function checkForm()
  {
      document.getElementsByName('answer')[0].value = 'Do not know';
      return true;
  }
</script>
